### ISSUE TITLE
Lista de patrocinadores não é responsiva 

### ISSUE THREAD

**Issue by jpjoao** [PHPSP/phpsp.org.br#23]
Ao menos no tablet a lista de patrocinadores no rodapé não quebra linha e fica “infinita” fora da visão.

**Comment by nawarian** [comment]
Em dispositivos com largura de tela `>= 769px` a lista de patrocinadores assume `dispaly: flex`, fazendo com que o css tente encaixar a todos numa única linha.

Eu submeti um pull request que agrupa os patrocinadores de 4 em 4, fazendo com que naturalmente quebrem de linha no quarto patrocinador quando a largura de tela for `>= 769px`.
