### ISSUE TITLE
Gerar target=_blank para links adicionados aos posts

### ISSUE THREAD

**Issue by Morkhusz** [PHPSP/phpsp.org.br#39]
Hoje todos os links criados dentro dos textos dos posts não possuem target _blank, o que pode ser um incômodo a alguns usuários pois ao clicar no link a página abre na aba atual do navegador, atrapalhando o ponto atual da leitura.
Favor comentar se parecer interessante ou fechar a issue caso seja irrelevante

**Comment by Morkhusz** [comment]
Como os posts são feitos em markdown, não encontrei uma forma de adicionar _blank aos links, caso alguém saiba como e quiser referenciar aqui eu posso implementar e criar um PR.
Dá pra fazer também com javascript para que todo <a> mande para um target _blank, se puder fazer assim me proponho a implementar, só gostaria de saber em qual arquivo coloco para que não afete outras paradas (ainda não manjo bem as paradas do source code daqui).
Abraços

**Comment by nawarian** [comment]
Fala @Morkhusz !! Esse caso é bem interessante. Nós aplicamos o mesmo no PODEntender ao fazer [post processing dos arquivos gerados](https://github.com/PODEntender/estatista/blob/master/src/Application/Service/FileProcessing/PostProcessFiles.php#L24-L48).

Esta solução não é ótima porque nos faz revisitar cada arquivo no gerado `afterBuild()`, carregar pra memória, fazer o replace e depois gravar novamente. Mas é uma opção.

Outra opção seria substituir o handler de Markdown que o Jigsaw usa. Para isso podemos implementar a interface existente e dar bind nela através do DI container.

Interface: https://github.com/tightenco/jigsaw/blob/master/src/Parsers/MarkdownParser.php

No `bootstrap.php` temos uma instância do Container, fazer:

```php
$container->bind(MarkdownParser::class, MyMarkdownParser::class);
```

**Comment by Morkhusz** [comment]
No PR #44 implementei a solução conforme a dica que você deixou, fiquei na dúvida sobre o namespace e o nome das classes.
Qualquer coisa sobre a implementação é só dar um toque que mudo as paradas para atender melhor a issue.
Abraço.

**Comment by nawarian** [comment]
Gostei muito da solução. Deixei algumas coisas lá pra ti. Mas fiquei muito animado em vez a implementação.
Com certeza vou portar pro [estatista](https://github.com/PODEntender/estatista) quando chegarmos a um ponto final

**Comment by xthiago** [comment]
Oi @Morkhusz, tudo bem?

Primeiramente gostaria de agradecer pela sua contribuição.

Pessoalmente não acho que é uma boa prática de UX incluir o `target=_blank` nos links. Jacob Nielsen, guru da usabilidade na web, trata sobre isso em seus já clássicos livros e em posts como [Top 10 Mistakes in Web Design](https://www.nngroup.com/articles/top-10-mistakes-web-design/). 

Esse artigo explica melhor ainda essa situação: [Beware of opening links in a new window](https://www.webcredible.com/blog/beware-opening-links-new-window/).

Em suma, é ruim porque:

- o usuário deve decidir se quer abrir uma nova janela ou não; ao obrigá-lo abrir, estamos interferindo na forma como ele consome conteúdo, muitas vezes atrapalhando abrindo mais abas; o usuário deve controlar suas abas, não os desenvolvedores;
  - e isso tem um efeito colateral mais forte: o botão _Voltar_ do navegador, que é a forma natural de voltarmos na página anterior, deixa de funcionar.
    - isso pode ser mais problemático ainda para pessoas com pouca familiaridade com a web (e multiplas abas);
- as pessoas geralmente fazem isso porque querem manter o usuário no site, mas para isso basta que o conteúdo seja relevante. 

Faz sentido para vocês? ;-)

**Comment by Morkhusz** [comment]
Interessante, cara.
Abri a issue pq em outros sites (medium e quora por exemplo) com artigos/posts é costumeiro que os links sejam abertos em outras páginas. Então achei interessante pra quem já está acostumado com este comportamento.
Pra mim fez sentido sim as referências, se vocês acharem melhor manter sem, assim será rs.

**Comment by nawarian** [comment]
Eu sou muito enviesado com o SEO e penso que o target=_blank pode influenciar no Bounce Rate, mas concordo profundamente que o conteúdo de qualidade deveria ser suficiente para atingir esse objetivo.

Ao mesmo tempo, o pull request pode ser extra relevante para que possamos em vez de adicionar um target=_blank, um `rel=nofollow` o que nos ajudaria a concentrar o link-juice dentro do site phpsp.org.br caso apliquemos a links internos

**Comment by ravanscafi** [comment]
Eu passei pela mesma problemática no meu blog. Ia colocar o `target=_blank` pra links externos somente. Depois vi o problema do rel="noopener" e no fim acabei por decidir só pelo `rel=nofollow` mesmo.

**Comment by jpjoao** [comment]
Opa @Morkhusz ,

Baseado no que foi falado pelo @nawarian, @xthiago e @ravanscafi acredito que fica "decidido" então não colocar o `target=_blank" mas sim o `rel=nofollow`.

Como boa parte do trabalho em parsear os links nos MD e tudo mais já foi iniciado no seu PR#44, seria bacana se você pudesse atualizar o código lá para refletir o que foi conversado aqui. Claro que, caso você ache mais fácil e prático, um novo PR pode ser criado.

Obrigado mais uma vez pela colaboração.

Abraços.

**Comment by Morkhusz** [comment]
Fechou então galera, valeu pela discussão!
Vou atualizar seguindo as orientações da galera ainda hoje, abraços!

**Comment by nawarian** [comment]
Acabei de aprovar e mergear o PR #44 . Muitíssimo obrigado aos envolvidos!!
