### ISSUE TITLE
Migrar para PHP 7.3

### ISSUE THREAD

**Issue by jpjoao** [PHPSP/phpsp.org.br#49]
Atualmente estamos utilizando PHP7.2, migrar para o 7.3 seria um passo interessante.

**Comment by Morkhusz** [comment]
Estou trabalhando nessa!

**Comment by Morkhusz** [comment]
Demorei um pouco (kkk) mas fiz um pr #93 atualizando o docker pro 7.4 mas tenho umas duvidas conforme comentei la, nao sei se e so isso que tem que fazer

*obs: foi mal ae galera, meu teclado esta sem os acentos kkk

**Comment by Morkhusz** [comment]
o @airtonzanon havia feito algo nesse sentido, nao?

**Comment by jpjoao** [comment]
Sim, isso já foi feito em outro MR.
