### ISSUE TITLE
Criar um feed RSS para o blog

### ISSUE THREAD

**Issue by ravanscafi** [PHPSP/phpsp.org.br#63]
Saiba mais em [O que é RSS?](https://www.infowester.com/rss.php).

Podemos nos basear por exemplo no trabalho que já foi feito no [blog do PODEntender](https://github.com/PODEntender/estatista/blob/master/src/Infrastructure/Application/StaticSite/FileProcessing/JigsawGenerateRssFeedAfterBuild.php). O resultado dá pra conferir [aqui](https://podentender.com/feed.xml).

**Comment by cjmz** [comment]
Vou olhar essa galera :)

**Comment by Morkhusz** [comment]
Fala meus lindos!
Como nosso amigo cjmz nao falou mais nada sobre o essa feature eu comecei a fazer aqui e ja criei o basico, falta apenas estruturar e deixar o codigo mais orientado a objetos, adicionar testes e tal...
Pra eu finalizar, poderiam me passar qual a estrutura que vcs querem do feed?
Digo, dentro de `<channel> <item> ` quais atributos vcs querem que coloque e tal?
Fechando isso creio que consigo finalizar ate o final de semana

**Comment by nawarian** [comment]
Acho que o mínimo seria ter title, description, link e guid (que pode ser o mesmo que o link).

Um exemplo minimasso que montei aqui funciona bem: `https://thephp.website/en/feed.xml`

**Comment by Morkhusz** [comment]
Se for mais nessa pegada já está quase pronto, eu criei uns builders seguindo a linha do PODEntender (inclusive te pedi review no particular).
Sobre title e description do blog em si alguma ideia? 
Nos itens vamos criar alguma regra pra criar uma descrição ou utilizar o texto todo já no feed?

**Comment by nawarian** [comment]
Title + Description do blog, recomendo criar algo no config.php; Nos itens, dá pra usar o title direto e só recordar os primeiros 200 chars do conteúdo, por exemplo.

**Comment by Morkhusz** [comment]
Sim, dessa maneira seria vida!
Mas um dos meus planos hoje e conseguir trazer mais gente pra escrever, venho falado com bastante gente e divulgado nos eventos da comunidade... E se sendo facil como e a galera ja nao faz, creio que colocar mais tags agora a galera faria menos ainda ou entao teriamos que ter isso no processo de revisao do artigo

**Comment by nawarian** [comment]
Dá pra botar valor default pras tags. Exemplo: `$title = $page->meta['title'] ?? $page->title` e `$descritpion = $page->meta['description'] ?? substr($page->content, 0, 200)`. Daí quem quiser otimizar pra SEO otimiza, quem não quiser fica de buenas

**Comment by Morkhusz** [comment]
Sim, sim... Sucesso então, farei isso

**Comment by Morkhusz** [comment]
Acho que podemos matar essa issue a não ser que tenham mais algo mapeado em relação a isso
