### ISSUE TITLE
Link do Slack incorreto

### ISSUE THREAD

**Issue by oliveiraev** [PHPSP/phpsp.org.br#68]
Oi, pessoal.

O link oferecido para entrar no slack da comunidade é inválido:

https://github.com/PHPSP/phpsp.org.br/blob/f0c876eab9111465338f94f60f07754b66729044/source/_contents/como-contribuir.md#L22

Parece que agora é obrigatório ter um email @phpsp.org.br para participar.

> ![image](https://user-images.githubusercontent.com/320460/65737829-2f13b080-e0b6-11e9-9ed6-1f0169f22824.png)

Nesse caso, que tal remover o link e incluir informações de como conseguir acesso ao workspace?

**Comment by airtonzanon** [comment]
Olá @oliveiraev ! Acabei de gerar um novo link, poderia criar um PR para corrigir isso?
O novo link é este https://join.slack.com/t/phpsp/shared_invite/enQtMzI2NjQxNTM4Mzg3LTA4ODU1NWI3ZDYzZWJjZmMzYjczZTc1YTc1ZWUwZjViMTExYzE3MGY3NDljZDYyMTdmNjMxMmM2MTE4ZWJhNmE

**Comment by ravanscafi** [comment]
Que péssimo isso, segundo o slack o link anterior não expirava nunca. Obrigado @airtonzanon

**Comment by oliveiraev** [comment]
> Olá @oliveiraev ! Acabei de gerar um novo link, poderia criar um PR para corrigir isso?
> O novo link é este https://join.slack.com/t/phpsp/shared_invite/enQtMzI2NjQxNTM4Mzg3LTA4ODU1NWI3ZDYzZWJjZmMzYjczZTc1YTc1ZWUwZjViMTExYzE3MGY3NDljZDYyMTdmNjMxMmM2MTE4ZWJhNmE

[aguardando review](https://github.com/PHPSP/phpsp.org.br/pull/69)
