### ISSUE TITLE
Acesso

### ISSUE THREAD

**Issue by cezinha1982** [PHPSP/phpsp.org.br#70]
Meu acesso expirou

**Comment by ravanscafi** [comment]
Qual acesso, @cezinha1982?

**Comment by cezinha1982** [comment]
[Image]

Bom dia o acesso a mapos, estalei mais ao acessar aparece o seguinte mensagem acesso expirou


Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by ravanscafi** [comment]
@cezinha1982, acho que a imagem não veio... consegue enviar pelo próprio github? respondendo ao email não apareceu.

o que seria o "mapos"?

**Comment by cezinha1982** [comment]
MapOs  sistema de ordem de serviço

**Comment by nawarian** [comment]
@cezinha1982 o PHPSP não tem nenhuma relação com este serviço MAPOS. Eu encontrei um outro lugar que talvez possa lhe ser útil: https://github.com/RamonSilva20/mapos

Boa sorte com seu problema.
